---
- name: check if this is a new install of jenkins with no credentials
  file:
    path: /var/lib/jenkins/credentials.xml
    state: touch

- name: "check if {{ credential.id }} exists"
  command: "awk /{{ credential.id|to_uuid }}/ /var/lib/jenkins/credentials.xml"
  register: check_cred
  changed_when: false

- name: "generate {{ credential.id }} credentials xml"
  template:
    src: credentials.xml.j2
    dest: /tmp/credentials.xml
  when: not check_cred.stdout | search(credential.id|to_uuid)

- name: "install {{ credential.id }} credentials"
  shell: "cat /tmp/credentials.xml | curl -u {{ jenkins_user }}:{{ jenkins_password }} -H \"Content-Type: text/xml\" -H {{ crumb_token }} -d @- -X POST \"{{ jenkins.master.node_url }}/credentials/store/system/domain/_/createCredentials\""
  when: not check_cred.stdout | search(credential.id|to_uuid)
  changed_when: false

- name: remove the temp credentials file
  file:
    path: /tmp/credentials.xml
    state: absent
